[package]
name = "pyri_state"
version = "0.1.0"
edition = "2021"
description = "A flexible alternative to `bevy_state`"
repository = "https://github.com/benfrankel/pyri_state"
license = "MIT OR Apache-2.0"
keywords = ["ecs", "game", "bevy"]
categories = ["game-engines", "data-structures"]

[features]
default = ["bevy_app", "bevy_reflect", "debug"]
bevy_app = ["dep:bevy_app", "pyri_state_derive/bevy_app"]
bevy_reflect = ["dep:bevy_reflect", "bevy_ecs/bevy_reflect"]
debug = ["dep:bevy_core", "dep:bevy_log", "pyri_state_derive/debug"]

[dependencies]
bevy_app = { version = "0.13", default-features = false, optional = true }
bevy_core = { version = "0.13", optional = true }
bevy_ecs = { version = "0.13", default-features = false }
bevy_log = { version = "0.13", optional = true }
bevy_reflect = { version = "0.13", optional = true }
pyri_state_derive = { version = "0.1", path = "derive" }

[dev-dependencies]
bevy = "0.13"
bevy_asset_loader = "0.20"
iyes_progress = "0.11"
