[package]
name = "pyri_state_derive"
version = "0.1.0"
edition = "2021"
description = "Derive macros for `pyri_state`"
repository = "https://github.com/benfrankel/pyri_state"
license = "MIT OR Apache-2.0"
keywords = ["ecs", "game", "bevy"]
categories = ["game-engines", "data-structures"]

[features]
bevy_app = ["dep:bevy_macro_utils"]

[lib]
proc-macro = true

[dependencies]
bevy_macro_utils = { version = "0.13", optional = true }
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", default-features = false, features = [
    "derive",
    "parsing",
    "printing",
    "proc-macro",
] }
